### ISSUE TITLE
Now working on my windows

### ISSUE THREAD

**Issue by Mosesboy2012** [AzT4NG/T4NG-REVERSE-DNS#1]
Please, is this for only Kali users or it can work on windows

**Comment by AzT4NG** [comment]
Yes it can be used. It works with Python and Nmap. However, you need to install Python and its code modules `subprocess`, `re`, `tqdm` and `colorama` with the pip package manager. Also, nmap must be installed. I do not recommend Windows because these operations are easier to do in a Linux-based operating system. Have a nice day.

**Comment by Mosesboy2012** [comment]
I have installed pythons and all the modules, so how will I install nmap?

**Comment by AzT4NG** [comment]
https://nmap.org/download.html#windows
